name: Publish Docker
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
          tags: user/app:latest
